### ISSUE TITLE
Proposal. Change testsmtp to MailHog.

### ISSUE THREAD

**Issue by opxwebdev** [esimonetti/SugarDockerized#85]
Hello Enrico,

For convenience, I suggest changing testsmtp to MailHog.
```
    mailhog:
        container_name: "sugar-mailhog"
        image: mailhog/mailhog:latest
        ports:
            - "8025:8025"
```
MailHog performs the same task as testsmtp, but it also has a simple interface for viewing emails.
